<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link href="./css/style.css" rel="stylesheet" type="text/css">
    <script defer type="text/javascript" src="/js/script.js"></script>
</head>
<body>
<h1>To Do App</h1>
<div>Your completed todos!</div>

<div id="to-do-list">
    <?php echo \Todoapp\ViewHelpers\CompletedViewHelper::completedTodosView($completedTodos); ?>
</div>
<a type="button" href="/">View outstanding todos</a>
</body>
</html>
