<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <script defer type="text/javascript" src="/js/script.js"></script>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
</head>
<body>
<h1>To Do App</h1>
<div>Your completed todos!</div>

<div id="to-do-list">
    <form class="todos" method="post" action="/completed/delete"><?php

        if (count($completedTodos) === 0) {
            echo '<p>You have no todos to delete</p>';
        } else {
            foreach ($completedTodos as $completedTodo) { ?>
                <p><span><?php echo $completedTodo["todo_name"]; ?>
                    <input type="submit" value="Delete">
                <input type="hidden" name="task" value="<?php $completedTodo["id"]; ?>">
                </span></p>
            <?php }
        } ?>
    </form>
</div>
</body>
</html>
