<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <script defer type="text/javascript" src="/public/js/script.js"></script>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
</head>
<body>
<h1>To Do App</h1>
<div>Add your to dos and check them off to stay organised</div>
<form id="todoInputForm">
    <input type="text" placeholder="Enter your todo here">
    <input type="submit" value="Add todo">
</form>

<div id="to-do-list">
    <ul class="todos"><?php foreach ($todos as $todo) { ?>
            <li><?php echo $todo["todo_name"]; ?>
                <input type="checkbox" name="<?php echo $todo["todo_name"]; ?>-checkbox" value="unchecked">
            </li>
        <?php } ?>
    </ul>
</div>
</body>
</html>
