<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href="./css/style.css" rel="stylesheet" type="text/css">
        <script defer src="/js/script.js"></script>
    </head>
    <body>
    <main>
        <div id="error-message">
            <h3><?php echo $errorMsg; ?></h3>
        </div>
        <h1>To Do App</h1>
        <p>Add your to dos and check them off to stay organised</p>
        <form id="todoInputForm" method="post" action="/add">
            <input type="text" name="todoUserInput" placeholder="Enter your todo here">
            <input type="submit" value="Add todo">
        </form>

        <div id="to-do-list">
            <form id="markCompleteForm" method="post" action="/markTodoComplete">
                <?php foreach ($todos as $todo) { ?>
                    <div>
                        <span><?php echo $todo["todo_name"]; ?></span>
                        <input name="todo[]" type="checkbox" value="<?php echo $todo["id"]; ?>">
                    </div>
                <?php } ?>
                <input type="submit" value="Mark as complete">
            </form>
        </div>
        <a type="button" href="/completed">View completed todos</a>
    </main>
    </body>
</html>
